#!/usr/bin/env bash
# Wrapper script to run yt-dlp via Docker

set -e

# Get git root directory
GIT_ROOT=$(git rev-parse --show-toplevel)

# Run yt-dlp in Docker, mounting git root as /data
docker run --rm \
  -v "$GIT_ROOT:/data" \
  -w /data \
  brefsearch-tools \
  "yt-dlp $*"
