#!/usr/bin/env bash
set -e

rsync \
  --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --copy-links \
  --compress \
  ./data/source/images/thumbnails \
  ./data/source/images/previews \
  pixelastic:/var/www/assets.pixelastic.com/brefsearch
