#!/usr/bin/env bash
set -e

rsync \
	--chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
	--verbose \
	--archive \
	--update \
	--delete \
	--prune-empty-dirs \
	--copy-links \
	--compress \
	../brefsearch-images/thumbnails \
	../brefsearch-images/animated \
	pixelastic:/var/www/assets.pixelastic.com/brefsearch
